CREATE TABLE ERS_REIMBURSEMENT_STATUS (
	REIMB_STATUS_ID NUMERIC PRIMARY KEY,
	REIMB_STATUS VARCHAR(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE (
	REIMB_TYPE_ID NUMERIC PRIMARY KEY,
	REIMB_TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE ERS_USER_ROLES (
	ERS_USER_ROLE_ID NUMERIC PRIMARY KEY,
	USER_ROLE VARCHAR(10) NOT NULL
);

CREATE TABLE ERS_USERS (
	ERS_USERS_ID SERIAL PRIMARY KEY,
	ERS_USERNAME VARCHAR(50) UNIQUE NOT NULL,
	ERS_PASSWORD VARCHAR NOT NULL,
	USER_FIRST_NAME VARCHAR(100) NOT NULL,
	USER_LAST_NAME VARCHAR(100) NOT NULL,
	USER_EMAIL VARCHAR(150) UNIQUE NOT NULL,
	USER_ROLE_ID NUMERIC REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT (
	REIMB_ID SERIAL PRIMARY KEY,
	REIMB_AMOUNT NUMERIC NOT NULL,
	REIMB_SUBMITTED TIMESTAMP NOT NULL,
	REIMB_RESOLVED TIMESTAMP,
	REIMB_DESCRIPTION VARCHAR(250),
	REIMB_AUTHOR NUMERIC REFERENCES ERS_USERS(ERS_USERS_ID) NOT NULL,
	REIMB_RESOLVER NUMERIC REFERENCES ERS_USERS(ERS_USERS_ID),
	REIMB_STATUS_ID NUMERIC REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID) NOT NULL,
	REIMB_TYPE_ID NUMERIC REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID) NOT NULL
);